### ISSUE TITLE
Update rocksdb to v0.19.0

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/aurora-engine#612] opened 2022-09-27 21:55 UTC
Out-of-bounds read when opening multiple column families with TTL.

Affected versions of this crate called the RocksDB C API rocksdb_open_column_families_with_ttl() with a pointer to a single integer TTL value, but one TTL value for each column family is expected. This is only relevant when using rocksdb::DBWithThreadMode::open_cf_descriptors_with_ttl() with multiple column families. This bug has been fixed in v0.19.0.

---

Reported by auditors. This doesn't affect us since we are not using `*_ttl` interface but still is worth updating (if not other breaking changes).

**Comment by birchmd** [comment] 2022-09-28 17:25
Note the auditor's report is a duplicate of an [open dependabot alert](https://github.com/aurora-is-near/aurora-engine/security/dependabot/80).

We cannot address this until after the upgrade happens in nearcore first (otherwise our tests do not compile because there are conflicting versions of `librocksdb-sys`). I have [poked them](https://github.com/near/nearcore/pull/7401#issuecomment-1261225629) about it.

**Comment by mfornet** [comment] 2022-09-28 18:05
Dependabot alert is private. Feel free to close this in favor of the alert, I understand is being tracked anyway, so there is no need to track it twice.

**Closed** 2023-10-16 10:34 UTC
