### ISSUE TITLE
Unable to call write function using Ether JS on localnet due to different key format.

### ISSUE THREAD

**Issue by karangorania** [aurora-is-near/aurora-engine#593] opened 2022-08-26 06:51 UTC
I have setup `Aurora Engine` on `NEAR`  localnet and `Aurora Relayer` for localnet, I deploy `ERC-20` contract using bytecode on `Aurora Engine`, using same contract address & encoded value of the account name(`aurora encode-address`) I am able to call read solidity function using this RPC `http://localhost:8545`  but unable to call write function using `Ether Js` because  `Near Private` key format is different.

If I use aurora Testnet RPC using Ether Js I am. able to execute read and write function because I have use Metamask Private Key.

As for as my understanding this is the issue because Near Secret Key formatted differ from Metamask Private Key.

How can I get key in Metamask Private Key format from Near Account Private Key, So I can execute read & write function using localnet.

Thank You

**Comment by birchmd** [comment] 2022-08-26 14:59
You do not need to use your NEAR key for anything other than running the relayer. You should be able to use a regular metamask key to interact with the EVM. Add http://localhost:8545/ as the RPC URL of a new network in the metamask UI. Note you'll have needed to configure your engine instance with a different chain Id from all other networks in your metamask.

Also, this is not an engine issue, so I am closing it.

**Closed by birchmd** 2022-08-26 14:59 UTC

**Comment by karangorania** [comment] 2022-08-26 15:05
Okay thanks, How can I get the funds for local net. For deploying contract
and interaction with Contract.

**Comment by birchmd** [comment] 2022-08-26 15:14
You can set the gas price equal to zero so you should not need ETH for many kinds of transactions.

If you do need ETH, then I recommend you compile the engine contract with the `integration-test` feature, then deploy it. This will enable a function called `mint_account` on the engine which can create a new address with some ETH already present.

Command to compile engine with `integration-test` feature:
```shell
aurora-is-near/aurora-engine$ cargo build --target wasm32-unknown-unknown --release --no-default-features --features=mainnet,integration-test -p aurora-engine -Z avoid-dev-deps
```

Example script invoking `mint_account`:
```python
import base64, subprocess, sys

NEAR_CLI = './node_modules/near-cli/bin/near'
ENGINE_ACCOUNT = 'evm.birchmd.testnet'
SIGNER_ACCOUNT = 'birchmd.testnet'

if __name__ == '__main__':
    address = bytes.fromhex(sys.argv[1])
    init_nonce = int(sys.argv[2]).to_bytes(8, byteorder='little')
    init_balance = int(sys.argv[3]).to_bytes(8, byteorder='little')
    input = base64.b64encode(address + init_nonce + init_balance)
    execution_result = subprocess.run([
        NEAR_CLI,
        '--networkId',
        'testnet',
        '--accountId',
        SIGNER_ACCOUNT,
        'call',
        '--base64',
        '--gas',
        '300000000000000',
        ENGINE_ACCOUNT,
        'mint_account',
        input
    ], capture_output=True)
    print(execution_result.stdout)
    print(execution_result.stderr)
```

**Comment by karangorania** [comment] 2022-08-26 15:22
Thanks a lot. I will try this & let you know how everything goes.

**Comment by TanyaSrivastava-Dipali** [comment] 2022-08-29 06:27
> 

@birchmd 
`aurora-is-near/aurora-engine$ cargo build --target wasm32-unknown-unknown --release --no-default-features --features=mainnet,integration-test -p aurora-engine -Z avoid-dev-deps`
I executed this command
Please tell where can I get newly created address which has some eth

**Comment by karangorania** [comment] 2022-08-29 07:06
@birchmd 
Which version you are using for localnet.

**Comment by birchmd** [comment] 2022-08-29 14:16
> @birchmd Which version you are using for localnet.

@karangorania You can use engine version 2.7.0 (the latest on the `master` branch)

**Comment by birchmd** [comment] 2022-08-29 14:19
> > 
> 
> @birchmd `aurora-is-near/aurora-engine$ cargo build --target wasm32-unknown-unknown --release --no-default-features --features=mainnet,integration-test -p aurora-engine -Z avoid-dev-deps` I'm using version 2.5.2 I executed this command Please tell where can I get newly created address and it's key which has some eth

@TanyaSrivastava-Dipali that command does not create any account. That command compiles the aurora-engine wasm artifact with an additional method enabled. You deploy that compiled wasm to your NEAR localnet (as the engine binary), then you will able to call a method called `mint_account`. That function allows you to directly set the nonce and balance of a given address. So you can create a key using any method you like (eg metamask), then set the ETH balance for the address associated with that key. See my example python script above for how to invoke `mint_account`.

**Comment by birchmd** [comment] 2022-08-29 17:28
@TanyaSrivastava-Dipali So you are getting a method not found error. This must mean you are not deploying the right wasm artifact. Make sure you deploy the one you compiled in step 3. Perhaps as a sanity check you can delete all the wasm artifacts you have, then compile and deploy the one which was re-created.

**Comment by karangorania** [comment] 2022-08-30 06:59
@birchmd I passed my metamask account address as arguments in mint functions. We have mint successfully, but it's showing zero ETH in Metamsk. I am using `RPC http://localhost:8545/` & `chain ID : 1313161556 `in metamask could you pls tell what should I do to connect to this RPC with metamask so I can perform all transactions ex: with Etherjs, Remix IDE etc...

**Comment by birchmd** [comment] 2022-08-30 14:42
@karangorania can you confirm the `mint_account` call worked by seeing a non-zero balance using the engine's `get_balance` function?

**Comment by TanyaSrivastava-Dipali** [comment] 2022-08-30 14:54
> @karangorania can you confirm the `mint_account` call worked by seeing a non-zero balance using the engine's `get_balance` function?
@birchmd 
Yes,It worked for us.
we are getting non-zero balance with `aurora  get-balance <address>` command
Still not getting ETH on metamask account on `http://localhost:8545/ ` RPC for that particular account.
Used chain ID : 1313161556

**Comment by karangorania** [comment] 2022-08-30 15:43
> What code is running at `http://localhost:8545/`? It must not be reading the balances properly

Aurora Relayer is running at `http://localhost:8545/`

**Comment by birchmd** [comment] 2022-08-30 15:50
Not sure what could be going wrong with getting the balance. It looks to me like the relayer should just call the same engine's `get_balance` function you are invoking.

https://github.com/aurora-is-near/aurora-relayer/blob/master/src/servers/database.ts#L159
https://github.com/aurora-is-near/aurora.js/blob/master/src/engine.ts#L417

Double check the relayer is using the correct engine account id and NEAR RPC url

**Comment by TanyaSrivastava-Dipali** [comment] 2022-08-30 16:24
Kindly get the attached screenshot of mint func
![Screenshot from 2022-08-30 14-36-54](https://user-images.githubusercontent.com/100181875/187486263-ec7adf16-5ce0-4f18-af74-890aa4e5d5ff.png)
See below screenshot I used correct engine account id and NEAR RPC url
![Screenshot from 2022-08-30 21-38-48](https://user-images.githubusercontent.com/100181875/187488671-f49b1e90-ce25-49e8-90cf-191e3d3f162d.png)
I'm able to call read fun like name(),balanceof() of erc 20 but unable to call mint(),transfer() etc
![Screenshot from 2022-08-30 21-48-14](https://user-images.githubusercontent.com/100181875/187488957-5cd0315c-d7b7-4946-9d44-465b8b5d9e34.png)
![Screenshot from 2022-08-30 21-53-41](https://user-images.githubusercontent.com/100181875/187489645-075d3ead-5e3f-486f-939b-7a2bd843a0fc.png)

**Comment by birchmd** [comment] 2022-08-30 19:04
What happens if instead of minting such a small amount of ETH, you try minting a more substantial amount. Note that the amount you pass in is in Wei, so 100 is very tiny. To give yourself 1 ETH you would pass in a value 1000000000000000000

**Comment by TanyaSrivastava-Dipali** [comment] 2022-08-30 19:35
Thanks @birchmd 
Now It's showing non-zero  ETH in metamask account.
Still unable to deploy contract using http://localhost:8545/
kindly have a look into attached screenshot
![Screenshot from 2022-08-31 01-03-08](https://user-images.githubusercontent.com/100181875/187527306-866d48df-c346-4174-9710-b919827db7cf.png)
![Screenshot from 2022-08-31 01-04-03](https://user-images.githubusercontent.com/100181875/187527339-33d8cb5a-b98c-4e29-8754-0fd862384faa.png)
could you please tell how to fix this

**Comment by birchmd** [comment] 2022-08-30 19:41
Nothing much helpful in that error message. What happens if you try to do the deploy using aurora cli instead of remix+metamask?

**Comment by TanyaSrivastava-Dipali** [comment] 2022-08-30 19:47
If I use aurora cli to deploy contract then it gets deployed easily  but for this I need to use bytecode of contract to deploy and function hashes to call function.
This is complex process.Thats why I'm trying relayer for web3 support.

**Comment by birchmd** [comment] 2022-08-30 20:38
Yes, I understand why it is nicer to use remix+metamask. I just wanted to understand if the issue was with the engine deployment or with the Relayer RPC. If it works via the cli and not via the Relayer RPC then it sounds like there is a problem with the Relayer RPC. You can see on the README for the Relayer repository on GitHub that we have officially deprecated it, so I do no think you should expect there will be fixes for the current JS version. Hopefully the new Golang version will work better for you.

In the meantime, perhaps a nicer CLI experience will help you. I've been working on https://github.com/birchmd/aurora-cli-rs It's lacking documentation, but there are Linux binaries attached to the releases and the `--help` flag will give some information about the various subcommands. You can try taking a look at the `near write solidity` subcommand. This allows you to pass arguments like you would in something like Remix and it creates the low-level transaction for you.

**Comment by TanyaSrivastava-Dipali** [comment] 2022-08-31 15:57
@birchmd 
According to my findings,I need not to mint ETH.Because I deployed an erc20 contract on aurora engine.Then I transferred ownership of contract to my metamask account address. I used that metamask account and its key to execute write functions like mint,transfer etc of erc20 token.Even I had not minted any ETH to the account what i used.  Still I'm able to execute write functions using etherjs with that metamas account and its private key.
It means there is no transaction fee in aurora.I checked via `near state ` command and got that transaction fee are getting paid from near account (aurora.test.near in my case).
But the problem is that private key format of aurora.test.near(from aurora.test.near.json file) is different from metamask account private key.That's why I'm unable to use aurora.test.near private key.Then I transfered my token ownership to my metamask account then it worked.
Now i want to know can i get private key(similar to metamask account key format) for my near account(aurora.test.near).So that I can execute all the functions without ownership transfer ?

one more thing,I'm still unable to deploy solidity smart contract using hardhat 0r remix+metamask using aurora-relayer RPC( http://localhost:8545/).
If I can call all functions of smart contract using etherjsthen why I'm unable to deploy solidity smart contract using hardhat 0r remix+metamask using aurora-relayer RPC( http://localhost:8545/)?

Kindly clear my doubts.

**Comment by birchmd** [comment] 2022-08-31 17:20
Yes, the first thing I said is that you shouldn't need ETH to make transactions back in [this comment](https://github.com/aurora-is-near/aurora-engine/issues/593#issuecomment-1228620784). I assumed you kept asking about it because you needed ETH for some other purpose besides paying transaction fees.

I do not know why the relayer RPC is not able to deploy contracts for you. As I said previously, if it is a problem with the relayer code then you will need to wait until the new golang implementation is released.

There is no way to use a metamask key with a NEAR account or vice versa.

**Comment by TanyaSrivastava-Dipali** [comment] 2022-09-03 12:27
> Yes, the first thing I said is that you shouldn't need ETH to make transactions back in [this comment](https://github.com/aurora-is-near/aurora-engine/issues/593#issuecomment-1228620784). I assumed you kept asking about it because you needed ETH for some other purpose besides paying transaction fees.
> 
> I do not know why the relayer RPC is not able to deploy contracts for you. As I said previously, if it is a problem with the relayer code then you will need to wait until the new golang implementation is released.
> 
> There is no way to use a metamask key with a NEAR account or vice versa.

@birchmd 
For aurora testnet & mainnet,We need to pay transaction fees in ETH.
But in my case  transaction fee are getting paid from near account (aurora.test.near).
What should I do next to pay transaction fee in eth for localnet (similar to testnet and mainnet)
Are aurora testnet and mainnet using rainbow bridge? or rainbow bridge is just for swap tokens.
i dinn't get any docs to  understand how testnet is working i.e how to setup aurora localnet,testnet etc.
kindly clear my doubts

**Comment by birchmd** [comment] 2022-09-05 12:23
On testnet and mainnet the fees are still paid in NEAR, but this is hidden from users. When you submit a transaction through the public Aurora RPC, a NEAR transaction is created by an account called `relay.aurora`. This transaction is what is executed on chain (and it is paid for in NEAR by `relay.aurora`), and the RPC translates the response back in a web3 compatible way. The reason the gas price is non-zero (i.e. users pay for their transactions using ETH) is to offset this NEAR cost that the Aurora infrastructure would otherwise have. That is to say, we can use the ETH revenue from users paying their fees to cover the NEAR cost we pay for actually submitting the transactions on-chain.

There is no way to avoid paying NEAR costs, even in a localnet setup (well you could make everything free I suppose by changing the minimum gas price to zero, or using the free fee schedule in the config, but I don't think this what you are asking). You can emulate the same set-up we have on testnet/mainnet by setting the gas price in your EVM transactions to a non-zero value. This will cause the users to pay for transactions in ETH, but you will still have to pay the NEAR cost as well, as I have explained above.

**Comment by TanyaSrivastava-Dipali** [comment] 2022-09-05 12:56
@birchmd 
Could you please tell How can I set the gas price in my EVM transactions to a non-zero value.Means In which file or repository (aurora relayer or aurora-engine)?

**Comment by birchmd** [comment] 2022-09-05 20:40
The gas price is set in the transaction, not in any config of the engine or relayer.

If you wanted the relayer to reject any transactions below a minimum gas price then I think you would need to make that modification to the relayer yourself (there is not a config for it currently).

**Comment by birchmd** [comment] 2022-11-17 14:37
The engine does not have a mechanism to enforce a minimum gas price; it would need to be done at the level of the relayer. If the relayer doesn't have this as a built-in configuration already then you'll have to add it yourself. It shouldn't be too difficult to add; simply check the gas price of the Eth transaction before sending to NEAR and do not have the relayer send it if the gas price is too low.
